bb-aem-integration-tests/src/test/java/com/cognifide/bdd/demo/aem/touchui/Siteadmin62Test.java
Need to fix tests that have problems when running on slow client environment (not on slow AEM instance)
=> AEM62 touch ui move page and copy page integration tests fix

bobcat/bb-core/src/main/java/com/cognifide/qa/bb/provider/selenium/webdriver/WebDriverType.java
Possibility to add webdriver proxy cookie directly after Webdriver instantiation (before running any tests) for any WebDriverType.
=> 75 - webdriver proxy cookie for other webdriver types

bb-aem-integration-tests/src/test/java/com/cognifide/bdd/demo/suite/BbAem62TouchUiSuite.java, bobcat/bb-aem-touch-ui/src/main/java/com/cognifide/qa/bb/aem/touch/pageobjects/touchui/dialogfields/text/ListDialogPanel.java
Add components that run smoothly on aem62 to corresponding aem62 integration test suite.
=> Add components to corresponding aem62 integration test suite

bb-aem-integration-tests/src/main/java/com/cognifide/bdd/demo/po/login/ProjectsScreen.java, bb-aem-integration-tests/src/main/java/com/cognifide/bdd/demo/po/login/UserDialog.java
=> minor css selector fixes to support aem 6.2 platform of bobcumber

bb-aem-integration-tests/pom.xml, bobcat/bb-cumber/src/main/java/com/cognifide/qa/bb/cumber/Bobcumber.java
Add RerunFailedTests checks to Bobcumber.
=> 97 - RerunFailedTests stabilization

bobcat/bb-aem-classic/src/main/java/com/cognifide/qa/bb/aem/dialog/classic/field/AemRichText.java
This change requires review of existing Rich Text related tests.
=> #131 Fixed frame switching in AemRichText

docs/_docs/modules.md, docs/_docs/modules/aem-classic-ui.md, docs/_docs/modules/aem-common.md, docs/_docs/modules/aem-touch-ui.md, docs/_docs/modules/core.md, docs/_docs/modules/cucumber.md, docs/_docs/modules/email.md, docs/_docs/modules/junit.md, docs/_docs/modules/traffic.md
Fulfill missing instruction on modules installation and dependencies.
=> Docs modules update

docs/_docs/modules/reports.md
Add documentation for reports module
- [x ] Documentation update
=> Update documentation for reports module

bb-core/src/main/java/com/cognifide/qa/bb/provider/selenium/webdriver/WebDriverType.java
Handle NPE when webdriver.cap.platformName is missing - for Appium based tests.
https://github.com/Cognifide/bobcat/issues/237
=> #237 Handle NPE when webdriver.cap.platformName is missing.

bb-aem-classic/src/main/java/com/cognifide/qa/bb/aem/ui/parsys/AemParsys.java, bb-aem-classic/src/main/java/com/cognifide/qa/bb/aem/ui/wcm/elements/SiteAdminGrid.java, bb-aem-touch-ui/src/main/java/com/cognifide/qa/bb/aem/touch/pageobjects/touchui/dialogfields/Select.java, bb-aem-touch-ui/src/main/java/com/cognifide/qa/bb/aem/touch/siteadmin/aem62/CreatePageWizard.java, bb-aem-touch-ui/src/main/java/com/cognifide/qa/bb/aem/touch/siteadmin/aem62/NavigatorDropdown.java, bb-aem-touch-ui/src/main/java/com/cognifide/qa/bb/aem/touch/siteadmin/aem62/SiteadminPage.java, bb-core/src/main/java/com/cognifide/qa/bb/mapper/field/PageObjectProviderHelper.java, bb-cumber/src/main/java/com/cognifide/qa/bb/cumber/StatisticsHelper.java, bb-email/src/test/java/com/cognifide/qa/bb/email/EmailTest.java, bb-traffic/src/test/java/com/cognifide/qa/bb/proxy/analyzer/predicate/RequestPredicateImplTest.java
Fix:
- https://sonarcloud.io/project/issues?id=com.cognifide.qa.bb&issues=AWT1cvvcJ00hBq3sdkpU&open=AWT1cvvcJ00hBq3sdkpU
- https://sonarcloud.io/project/issues?id=com.cognifide.qa.bb&issues=AWT1cv4YJ00hBq3sdkpw&open=AWT1cv4YJ00hBq3sdkpw
- https://sonarcloud.io/project/issues?id=com.cognifide.qa.bb&issues=AWT1cvwrJ00hBq3sdkpW&open=AWT1cvwrJ00hBq3sdkpW
- https://sonarcloud.io/project/issues?id=com.cognifide.qa.bb&issues=AWT1cvTNJ00hBq3sdknX&open=AWT1cvTNJ00hBq3sdknX
=> Fix bugs detected by Sonarcloud after merging branch 250

bb-core/src/main/java/com/cognifide/qa/bb/RunWithJunit5.java, bb-core/src/main/java/com/cognifide/qa/bb/loadable/mapper/TestObjectTypeListener.java, bb-junit5/pom.xml, bb-junit5/src/main/java/com/cognifide/qa/bb/junit5/guice/GuiceExtension.java, bb-junit5/src/main/java/com/cognifide/qa/bb/junit5/guice/InjectorUtils.java, bb-junit5/src/main/java/com/cognifide/qa/bb/junit5/guice/Modules.java, bb-junit5/src/main/java/com/cognifide/qa/bb/junit5/guice/WebdriverCloseExtension.java, bb-junit5/src/main/resources/META-INF/services/org.junit.jupiter.api.extension.Extension, pom.xml
=> 153 junit5 support

bb-junit5/pom.xml, bb-junit5/src/main/java/com/cognifide/qa/bb/junit5/JUnit5Constants.java, bb-junit5/src/main/java/com/cognifide/qa/bb/junit5/allure/AllureConstants.java, bb-junit5/src/main/java/com/cognifide/qa/bb/junit5/allure/EnviromentInfoExtension.java, bb-junit5/src/main/java/com/cognifide/qa/bb/junit5/allure/ScreenshotExtension.java, bb-junit5/src/main/java/com/cognifide/qa/bb/junit5/guice/GuiceExtension.java, bb-junit5/src/main/java/com/cognifide/qa/bb/junit5/selenium/WebdriverCloseExtension.java, bb-junit5/src/main/resources/META-INF/services/org.junit.jupiter.api.extension.Extension, pom.xml
Allure support for JUnit 5
Two properties
allure.report: if true allure will prepare files
allure.create.enviroment - if true allure will add properties to the report (generate environment.properties in results directory)
=> 265 allure for junit5

docs/_data/navigation.yml, docs/_docs/allure.md, docs/_docs/modules.md, docs/_docs/modules/junit5.md, docs/_docs/templates.md
Documentation to be merge after release
=> #265 junit 5 and allure docs

bb-aem-touch-ui/pom.xml, bb-core/pom.xml, bb-cumber/pom.xml, pom.xml
=> Revert "#274 upgrade of cucumber version to 3.0.2"

bb-reports/src/main/java/com/cognifide/qa/bb/logging/WebDriverLogger.java, pom.xml
Update Selenium version to 3.14.0.
Update WebDriverLogger to fit the updated WebdriverEventListener.
https://github.com/Cognifide/bobcat/issues/270
=> Update Selenium version to 3.14.0.

bb-email/pom.xml, bb-email/src/main/java/com/cognifide/qa/bb/email/CommonEmailDataPredicates.java, bb-email/src/main/java/com/cognifide/qa/bb/email/EmailData.java, bb-email/src/main/java/com/cognifide/qa/bb/email/EmailDataFactory.java, bb-email/src/test/java/com/cognifide/qa/bb/email/CommonEmailDataPredicatesTest.java, bb-email/src/test/java/com/cognifide/qa/bb/email/helpers/EmailDataGenerator.java, bb-email/src/test/java/com/cognifide/qa/bb/module/PropertiesLoaderModule.java, pom.xml
Cleanup of dependencies for the bb-email module
Bumped most dependencies
Migrated from joda-time to java.time
https://github.com/Cognifide/bobcat/issues/243
=> 243 email dependencies check

bb-aem-classic/pom.xml, bb-aem-touch-ui/src/main/java/com/cognifide/qa/bb/aem/touch/package-info.java, bb-core/src/main/java/com/cognifide/qa/bb/provider/selenium/webdriver/WebDriverType.java, bb-core/src/main/java/com/cognifide/qa/bb/provider/selenium/webdriver/WebDriverWrapper.java, bb-reports/pom.xml, bb-reports/src/main/java/com/cognifide/qa/bb/logging/package-info.java, bb-traffic/pom.xml, pom.xml
All Bobcat dependencies were updated to their latest versions.
#243
=> 243 dependencies cleanup

bb-aem-touch-ui/src/main/java/com/cognifide/qa/bb/aem/touch/siteadmin/aem61/CreatePageWizard.java, bb-aem-touch-ui/src/main/java/com/cognifide/qa/bb/aem/touch/siteadmin/aem61/ReplicateLaterWindow.java, bb-aem-touch-ui/src/main/java/com/cognifide/qa/bb/aem/touch/siteadmin/aem61/SiteadminPage.java, bb-aem-touch-ui/src/main/java/com/cognifide/qa/bb/aem/touch/siteadmin/aem61/calendar/YearMonthPicker.java, bb-aem-touch-ui/src/main/java/com/cognifide/qa/bb/aem/touch/siteadmin/aem62/MovePageWizard.java, bb-aem-touch-ui/src/main/java/com/cognifide/qa/bb/aem/touch/siteadmin/aem62/ReplicatePageWizard.java, bb-aem-touch-ui/src/main/java/com/cognifide/qa/bb/aem/touch/siteadmin/aem62/SiteadminPage.java, bb-core/src/main/java/com/cognifide/qa/bb/loadable/package-info.java, bb-core/src/main/java/com/cognifide/qa/bb/modules/LoadablesModule.java, bb-core/src/main/java/com/cognifide/qa/bb/modules/PageObjectsModule.java
This PR deprecates Loadable feature, the corresponding package and module.
#228
=> #228 Loadable package and module deprecated

bb-aem-common/src/main/java/com/cognifide/qa/bb/aem/package-info.java, bb-aem-common/src/main/java/com/cognifide/qa/bb/constants/package-info.java, bb-aem-common/src/main/java/com/cognifide/qa/bb/jcr/package-info.java, bb-aem-common/src/main/java/com/cognifide/qa/bb/provider/jcr/package-info.java, bb-annotations/src/main/java/com/cognifide/qa/bb/qualifier/Retry.java, bb-core/src/main/java/com/cognifide/qa/bb/RunWithJunit5.java, bb-core/src/main/java/com/cognifide/qa/bb/config/ConfigStrategyProvider.java, bb-core/src/main/java/com/cognifide/qa/bb/config/LegacyConfig.java, bb-core/src/main/java/com/cognifide/qa/bb/config/PropertyBinder.java, bb-core/src/main/java/com/cognifide/qa/bb/modules/PropertyModule.java, bb-core/src/main/java/com/cognifide/qa/bb/reporter/Reporter.java, bb-core/src/test/java/com/cognifide/qa/bb/config/ConfigStrategyProviderTest.java, bb-cumber/src/main/java/com/cognifide/qa/bb/assertions/soft/package-info.java, bb-cumber/src/main/java/com/cognifide/qa/bb/cumber/rerun/package-info.java, bb-integration-tests/src/test/java/com/cognifide/qa/bb/core/config/YamlConfigTest.java, bb-integration-tests/src/test/resources/config.yaml, bb-junit/src/main/java/com/cognifide/qa/bb/junit/package-info.java, docs/_data/navigation.yml, docs/_docs/modules.md, docs/_docs/modules/aem-classic-ui.md, docs/_docs/modules/aem-common.md, docs/_docs/modules/aem-touch-ui.md, docs/_docs/modules/junit.md, docs/_docs/modules/reports.md
Deprecates a bunch of Bobcat modules (put as EOL starting from next release) and packages.
Additionally switches configuration to YAML-based one by default.
#228
=> 228 deprecation

bb-core/src/main/java/com/cognifide/qa/bb/modules/BobcatRunModule.java
=> #292 runmodes working

bb-junit5/src/main/java/com/cognifide/qa/bb/junit5/selenium/WebdriverCloseExtension.java
Fix for #306 
#306 
~~My change requires a change to the documentation.~~
~~I have updated the documentation accordingly.~~
~~I have added tests to cover my changes.~~
=> #306 Fixed WebDriverCloseExtension - it does not open unnecessary sessions now

docs/_data/navigation.yml, docs/_docs/getting-started.md, docs/_docs/guides/first-test.md, docs/index.html
Grammar and typo fixes for the first tutorial and introductory page
=> Basic documentation fixes

docs/_docs/guides/first-aem-test.md
=> Basic documentation fixes v2

bb-junit5/pom.xml, bb-junit5/src/main/java/com/cognifide/qa/bb/junit5/selenium/WebdriverCloseExtension.java, bb-junit5/src/test/java/com/cognifide/qa/bb/junit5/selenium/WebdriverCloseExtensionTest.java
=> The actual fix for WebDriverCloseExtension issues #306

pom.xml
Jetty bumped to latest version
Security fixes
=> Jetty updated to latest version

bb-aem-64/src/main/java/com/cognifide/qa/bb/aem/core/component/GlobalBarImpl.java, bb-aem-64/src/main/java/com/cognifide/qa/bb/aem/core/component/dialog/DialogFieldRetrieverImpl.java, bb-aem-64sp2/pom.xml, bb-aem-64sp2/src/main/java/com/cognifide/qa/bb/aem64sp2/core/component/dialog/DialogFieldRetrieverImpl.java, bb-aem-64sp2/src/main/java/com/cognifide/qa/bb/aem64sp2/core/modules/Aem64SP2FullModule.java, bb-aem-64sp2/src/main/java/com/cognifide/qa/bb/aem64sp2/core/modules/AemComponentModule.java, pom.xml
=> AEM 6.4 SP2

bb-core/src/main/java/com/cognifide/qa/bb/config/ConfigStrategy.java, bb-core/src/main/java/com/cognifide/qa/bb/constants/ConfigKeys.java, bb-core/src/main/resources/default.yaml, bb-core/src/test/java/com/cognifide/qa/bb/config/ConfigStrategyTest.java, bb-integration-tests/src/main/java/com/cognifide/qa/bb/core/modules/TestModule.java, bb-integration-tests/src/test/java/com/cognifide/qa/bb/core/cookies/CookiesWithDisabledAutoLoadTest.java, bb-integration-tests/src/test/java/com/cognifide/qa/bb/core/qualifier/findpageobject/FindPageObjectInterfaceTest.java, bb-integration-tests/src/test/java/com/cognifide/qa/bb/core/qualifier/findpageobject/FindPageObjectTest.java, bb-integration-tests/src/test/java/com/cognifide/qa/bb/core/scope/current/ScopeCurrentTest.java, bb-integration-tests/src/test/java/com/cognifide/qa/bb/core/wait/BobcatWaitTest.java, bb-integration-tests/src/test/resources/html/com/cognifide/qa/bb/core/wait/page.html
- timings properties are now loaded correctly as System properties from Bobcat config file
- added missing tests
#328 
~~- My change requires a change to the documentation.~~
~~- I have updated the documentation accordingly.~~
=> Load timings correctly from the config file

bb-aem-64/pom.xml, bb-aem-64sp2/pom.xml, bb-aem-65/pom.xml, bb-aem-core/pom.xml, bb-core/pom.xml, bb-email/pom.xml, bb-integration-tests/pom.xml, bb-junit5/pom.xml, bb-traffic/pom.xml, pom.xml
- cleaned up the output of the Maven build
- added deprecation option to the compiler args
- more readable build logs
~~- My change requires a change to the documentation.~~
~~- I have updated the documentation accordingly.~~
~~-  I have added tests to cover my changes.~~
=> Clean up Maven build

bb-core/pom.xml, pom.xml
- removed unused dependencies (declare, not used)
- added Guava to bb-core to avoid conflicts with transient dependencies
Required after dependencies update + cleaning up the dependencies mess a bit
~~- My change requires a change to the documentation.~~
~~- I have updated the documentation accordingly.~~
~~- I have added tests to cover my changes.~~
=> Clean up Maven dependencies

.travis.yml, run_browserstack_tests.sh
Update Travis config
Changes due to BrowserStack integration
=> Browserstack tests

.gitignore, .travis.yml, bb-aem-64/pom.xml, bb-aem-64sp2/pom.xml, bb-aem-65/pom.xml, bb-aem-core/pom.xml, bb-appium/pom.xml, bb-core/pom.xml, bb-email/pom.xml, bb-integration-tests/pom.xml, bb-junit5/pom.xml, bb-traffic/pom.xml, pom.xml
Jacoco setup to measure code coverage
Better overview on the quality of the project
=> Jacoco setup

bb-aem-65/src/main/java/com/cognifide/qa/bb/aem/core/component/dialog/dialogfields/DefaultMultifield.java, bb-aem-65/src/main/java/com/cognifide/qa/bb/aem/core/component/dialog/dialogfields/DefaultPathBrowser.java, bb-aem-65/src/main/java/com/cognifide/qa/bb/aem/core/component/dialog/dialogfields/DefaultTagBrowser.java, bb-aem-65/src/main/java/com/cognifide/qa/bb/aem/core/component/dialog/dialogfields/Fields.java, bb-aem-65/src/main/java/com/cognifide/qa/bb/aem/core/component/dialog/dialogfields/Locators.java, bb-aem-65/src/main/java/com/cognifide/qa/bb/aem/core/modules/fields/FieldsRegistryModule.java, bb-aem-65/src/main/java/com/cognifide/qa/bb/aem/core/pages/sling/CreatePage.java, bb-aem-65/src/main/java/com/cognifide/qa/bb/aem/core/pages/sling/DeletePage.java, bb-aem-65/src/main/java/com/cognifide/qa/bb/aem/core/pages/sling/PageXMLParserHandler.java, bb-aem-core/src/main/java/com/cognifide/qa/bb/aem/core/component/dialog/dialogfields/TagBrowser.java, docs/_docs/modules/aem/componentconfiguration.md
This PR enables Bobcat to handle the List from Core Components and is required for it's BB tests to work https://github.com/Cognifide/bobcat-aem-tests/pull/7 for https://github.com/Cognifide/bobcat/issues/373
=> Core components list handling fixes

bb-aem-65/src/main/java/com/cognifide/qa/bb/aem/core/component/dialog/dialogfields/DefaultCheckbox.java, bb-aem-65/src/main/java/com/cognifide/qa/bb/aem/core/component/dialog/dialogfields/DefaultMultifield.java, bb-aem-65/src/main/java/com/cognifide/qa/bb/aem/core/component/dialog/dialogfields/DefaultPathBrowser.java, bb-aem-65/src/main/java/com/cognifide/qa/bb/aem/core/component/dialog/dialogfields/DefaultTagBrowser.java, bb-aem-65/src/main/java/com/cognifide/qa/bb/aem/core/component/dialog/dialogfields/Fields.java, bb-aem-65/src/main/java/com/cognifide/qa/bb/aem/core/modules/fields/FieldsRegistryModule.java, bb-aem-65/src/main/java/com/cognifide/qa/bb/aem/core/pages/sling/CreatePage.java, bb-aem-65/src/main/java/com/cognifide/qa/bb/aem/core/pages/sling/DeletePage.java, bb-aem-65/src/main/java/com/cognifide/qa/bb/aem/core/pages/sling/PageXMLParserHandler.java, bb-aem-core/src/main/java/com/cognifide/qa/bb/aem/core/component/dialog/dialogfields/TagBrowser.java, bb-integration-tests/pom.xml, docs/_docs/modules/aem/componentconfiguration.md
Related to:
https://github.com/Cognifide/bobcat/issues/373
Fixes required for Image Core Component tests to work - https://github.com/Cognifide/bobcat-aem-tests/pull/8
=> Core components image handling fixes

bb-aem-65/src/main/java/com/cognifide/qa/bb/aem/core/component/dialog/dialogfields/rte/Lists.java
=> Introduce support for using RTE list options without changing the text

bb-aem-65/src/main/java/com/cognifide/qa/bb/aem/core/component/dialog/DefaultDialogFieldRetriever.java, bb-aem-65/src/main/java/com/cognifide/qa/bb/aem/core/component/dialog/dialogfields/ContentFragmentPathBrowserImpl.java, bb-aem-65/src/main/java/com/cognifide/qa/bb/aem/core/component/dialog/dialogfields/DefaultContentFragmentPathBrowser.java, bb-aem-65/src/main/java/com/cognifide/qa/bb/aem/core/component/dialog/dialogfields/DefaultMultifield.java, bb-aem-65/src/main/java/com/cognifide/qa/bb/aem/core/component/dialog/dialogfields/DefaultNumberInput.java, bb-aem-65/src/main/java/com/cognifide/qa/bb/aem/core/component/dialog/dialogfields/DefaultSelect.java, bb-aem-65/src/main/java/com/cognifide/qa/bb/aem/core/component/dialog/dialogfields/DefaultTextfield.java, bb-aem-65/src/main/java/com/cognifide/qa/bb/aem/core/component/dialog/dialogfields/Fields.java, bb-aem-65/src/main/java/com/cognifide/qa/bb/aem/core/component/dialog/dialogfields/Locators.java, bb-aem-65/src/main/java/com/cognifide/qa/bb/aem/core/modules/fields/DialogFieldsModule.java, bb-aem-65/src/main/java/com/cognifide/qa/bb/aem/core/modules/fields/FieldsRegistryModule.java, bb-aem-core/src/main/java/com/cognifide/qa/bb/aem/core/component/dialog/dialogfields/ContentFragmentPathBrowser.java, bb-aem-core/src/main/java/com/cognifide/qa/bb/aem/core/component/dialog/dialogfields/NumberInput.java
Fixes for BB enabling the handling of Content Fragment core component
Required for: https://github.com/Cognifide/bobcat-aem-tests/pull/13
Part of https://github.com/Cognifide/bobcat/issues/373
=> Core components content fragment handling fixes
